<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Auxilia.Application\Auxilia.Application.csproj" />
    <ProjectReference Include="..\Auxilia.Contracts\Auxilia.Contracts.csproj" />
    <ProjectReference Include="..\Auxilia.Infrastructure\Auxilia.Infrastructure.csproj" />
    <ProjectReference Include="..\Auxilia.Persistence.Catalog\Auxilia.Persistence.Catalog.csproj" />
    <ProjectReference Include="..\Auxilia.Persistence.Tenant\Auxilia.Persistence.Tenant.csproj" />
    <ProjectReference Include="..\Auxilia.ServiceDefaults\Auxilia.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
