<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Auxilia.Api\Auxilia.Api.csproj" />
    <ProjectReference Include="..\Auxilia.Tests.Common\Auxilia.Tests.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Redis" />
  </ItemGroup>

</Project>
