<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Auxilia.Application\Auxilia.Application.csproj" />
    <ProjectReference Include="..\Auxilia.Domain\Auxilia.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Fluid.Core" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Rebus" />
    <PackageReference Include="Rebus.PostgreSql" />
    <PackageReference Include="Rebus.RabbitMq" />
    <PackageReference Include="Rebus.ServiceProvider" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Auxilia.Infrastructure.Tests" />
  </ItemGroup>

</Project>
