import type { AbstractIntlMessages } from "next-intl";

import en from "../../messages/en.json";
import it from "../../messages/it.json";

/** Flat bundle as served by `GET /api/v1/i18n/{lang}`: key → text (`nav.cases`, `Save`, `errors.AUX-12005`). */
export type FlatMessages = Record<string, string>;

/** Languages of the static fallback bundles (EN and IT are mandatory for every key). */
export const FALLBACK_LOCALES = ["it", "en"] as const;

const fallbacks: Record<string, FlatMessages> = { en, it };

/** The static bundle of a language (generated by `pnpm i18n:sync`); English for any other language. */
export function fallbackMessages(locale: string): FlatMessages {
  return fallbacks[locale] ?? en;
}

/**
 * next-intl reads dots as namespaces: `nav.cases` becomes `{ nav: { cases } }`, so `t("nav.cases")` finds it. A key
 * that is also the prefix of other keys keeps the namespace (the backend seed has none; a test watches it).
 */
export function unflatten(flat: FlatMessages): AbstractIntlMessages {
  const root: Record<string, unknown> = {};
  const keys = Object.keys(flat).sort((a, b) => b.split(".").length - a.split(".").length);
  for (const key of keys) {
    const parts = key.split(".");
    let node = root;
    let blocked = false;
    for (const part of parts.slice(0, -1)) {
      const next = node[part];
      if (typeof next === "string") {
        blocked = true;
        break;
      }

      node = (next as Record<string, unknown> | undefined) ?? (node[part] = {});
    }

    const leaf = parts.at(-1)!;
    if (!blocked && node[leaf] === undefined) {
      node[leaf] = flat[key];
    }
  }

  return root as AbstractIntlMessages;
}
