-- ============================================================================
-- AUXILIA DATABASE REDESIGN - V2 PRODUCTION DDL (POSTGRESQL NATIVE)
-- File: sysadmin/postgres/script/01_schema_v2.sql
-- ============================================================================

-- 1. Estensioni necessarie
CREATE EXTENSION IF NOT EXISTS "btree_gist";
CREATE EXTENSION IF NOT EXISTS "citext";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Schemi logici di dominio
CREATE SCHEMA IF NOT EXISTS iam;
CREATE SCHEMA IF NOT EXISTS dossier;
CREATE SCHEMA IF NOT EXISTS dms;
CREATE SCHEMA IF NOT EXISTS scheduling;
CREATE SCHEMA IF NOT EXISTS system;

-- ============================================================================
-- FUNZIONE AUDIT & CONCORRENZA
-- ============================================================================

CREATE OR REPLACE FUNCTION system.touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = clock_timestamp();
    IF TG_OP = 'UPDATE' AND (NEW IS DISTINCT FROM OLD) THEN
        NEW.version = OLD.version + 1;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- SCHEMA: system (Configurazioni, i18n, UI, Audit)
-- ============================================================================

CREATE TABLE IF NOT EXISTS system.languages (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(10) NOT NULL,
    name varchar(50) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uq_languages_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS system.resource_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_name citext NOT NULL,
    category varchar(100) NOT NULL DEFAULT 'General',
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uq_resource_keys_name UNIQUE (key_name)
);

CREATE TABLE IF NOT EXISTS system.resource_translations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_key_id integer NOT NULL REFERENCES system.resource_keys(id) ON DELETE CASCADE,
    language_id smallint NOT NULL REFERENCES system.languages(id) ON DELETE CASCADE,
    translation_value text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz,
    CONSTRAINT uq_resource_translation_key_lang UNIQUE (resource_key_id, language_id)
);
CREATE INDEX IF NOT EXISTS ix_resource_translations_lang ON system.resource_translations(language_id);

CREATE TABLE IF NOT EXISTS system.configurations (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key varchar(100) NOT NULL,
    value text NOT NULL,
    data_type varchar(20) NOT NULL DEFAULT 'string' 
        CHECK (data_type IN ('string', 'integer', 'boolean', 'json', 'color')),
    description varchar(255),
    is_public boolean NOT NULL DEFAULT false,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    version integer NOT NULL DEFAULT 1,
    CONSTRAINT uq_configurations_key UNIQUE (key)
);
CREATE INDEX IF NOT EXISTS ix_configurations_key ON system.configurations(key);

CREATE TABLE IF NOT EXISTS system.email_settings (
    id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    smtp_server varchar(255) NOT NULL,
    smtp_port integer NOT NULL CHECK (smtp_port BETWEEN 1 AND 65535),
    enable_ssl boolean NOT NULL DEFAULT true,
    username varchar(255) NOT NULL,
    password_encrypted text NOT NULL,
    from_email citext NOT NULL CHECK (from_email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
    from_name varchar(150) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- Catalogo Viste / Schermate UI (unifica ModuleConfigurations e PageConfigurations)
CREATE TABLE IF NOT EXISTS system.ui_views (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id smallint REFERENCES system.ui_views(id) ON DELETE CASCADE,
    code varchar(50) NOT NULL,
    route_path varchar(150) NOT NULL,
    display_name_key varchar(100) NOT NULL,
    icon_name varchar(50),
    sort_order smallint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uq_ui_views_code UNIQUE (code)
);
CREATE INDEX IF NOT EXISTS ix_ui_views_parent ON system.ui_views(parent_id);

-- ============================================================================
-- SCHEMA: iam (Identity & Access Management)
-- ============================================================================

CREATE TABLE IF NOT EXISTS iam.roles (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    description text,
    CONSTRAINT uq_roles_code UNIQUE (code)
);

-- Permessi per Ruolo su Viste e Griglie UI
CREATE TABLE IF NOT EXISTS system.ui_role_permissions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id smallint NOT NULL REFERENCES iam.roles(id) ON DELETE CASCADE,
    view_id smallint NOT NULL REFERENCES system.ui_views(id) ON DELETE CASCADE,
    is_enabled boolean NOT NULL DEFAULT true,
    grid_configuration jsonb CHECK (
        grid_configuration IS NULL OR jsonb_typeof(grid_configuration) = 'array'
    ),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uq_role_view UNIQUE (role_id, view_id)
);
CREATE INDEX IF NOT EXISTS ix_ui_role_permissions_lookup ON system.ui_role_permissions(role_id, view_id) WHERE is_enabled = true;

CREATE TABLE IF NOT EXISTS iam.specializations (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id smallint NOT NULL REFERENCES iam.roles(id) ON DELETE RESTRICT,
    name varchar(100) NOT NULL,
    description text,
    email citext,
    work_phone varchar(30),
    has_private_dossiers boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uq_specializations_role_name UNIQUE (role_id, name)
);

CREATE TABLE IF NOT EXISTS iam.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username citext,
    password_hash varchar(255),
    
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    email citext,
    phone varchar(100),
    fiscal_code varchar(30),
    date_of_birth date,
    
    profile_image_path text,
    preferred_language_id smallint NOT NULL DEFAULT 1 REFERENCES system.languages(id) ON DELETE RESTRICT,
    privacy_consent boolean NOT NULL DEFAULT false,
    privacy_consent_at timestamptz,
    
    is_active boolean NOT NULL DEFAULT true,
    is_default_employee boolean NOT NULL DEFAULT false,
    can_configure_system boolean NOT NULL DEFAULT false,
    
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz,
    version integer NOT NULL DEFAULT 1,
    
    CONSTRAINT uq_users_fiscal_code UNIQUE (fiscal_code),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_login_creds CHECK (
        (username IS NULL AND password_hash IS NULL) OR 
        (username IS NOT NULL AND password_hash IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_not_null ON iam.users(email) WHERE email IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_users_names ON iam.users(last_name, first_name);
CREATE INDEX IF NOT EXISTS ix_users_metadata_gin ON iam.users USING gin (metadata);

CREATE OR REPLACE TRIGGER trg_users_touch
BEFORE UPDATE ON iam.users
FOR EACH ROW EXECUTE FUNCTION system.touch_updated_at();

CREATE TABLE IF NOT EXISTS iam.user_roles (
    user_id integer NOT NULL REFERENCES iam.users(id) ON DELETE CASCADE,
    role_id smallint NOT NULL REFERENCES iam.roles(id) ON DELETE CASCADE,
    assigned_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS iam.user_specializations (
    user_id integer NOT NULL REFERENCES iam.users(id) ON DELETE CASCADE,
    specialization_id smallint NOT NULL REFERENCES iam.specializations(id) ON DELETE CASCADE,
    assigned_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (user_id, specialization_id)
);

CREATE TABLE IF NOT EXISTS iam.user_assignments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id integer NOT NULL REFERENCES iam.users(id) ON DELETE CASCADE,
    assigned_to_user_id integer NOT NULL REFERENCES iam.users(id) ON DELETE RESTRICT,
    assignment_role varchar(50) NOT NULL DEFAULT 'Operator',
    assigned_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_active_client_assignment UNIQUE (client_id, assigned_to_user_id, assignment_role)
);
CREATE INDEX IF NOT EXISTS ix_user_assignments_operator ON iam.user_assignments(assigned_to_user_id) WHERE is_active = true;

CREATE TABLE IF NOT EXISTS iam.user_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES iam.users(id) ON DELETE CASCADE,
    connection_id text NOT NULL,
    ip_address inet,
    user_agent text,
    login_time timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_activity timestamptz NOT NULL DEFAULT clock_timestamp(),
    is_active boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS ix_user_sessions_lookup ON iam.user_sessions(user_id, is_active);

CREATE TABLE IF NOT EXISTS iam.registration_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    email citext NOT NULL,
    phone varchar(100) NOT NULL,
    fiscal_code varchar(30) NOT NULL,
    date_of_birth date NOT NULL,
    request_date timestamptz NOT NULL DEFAULT clock_timestamp(),
    is_processed boolean NOT NULL DEFAULT false,
    processed_by_user_id integer REFERENCES iam.users(id) ON DELETE SET NULL,
    processed_date timestamptz,
    notes text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS ix_registration_requests_email ON iam.registration_requests(email);

-- ============================================================================
-- SCHEMA: dossier (Servizi e Pratiche CAF / Patronato)
-- ============================================================================

CREATE TABLE IF NOT EXISTS dossier.service_categories (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    description text,
    CONSTRAINT uq_service_categories_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS dossier.services (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id smallint REFERENCES dossier.service_categories(id) ON DELETE RESTRICT,
    specialization_id smallint REFERENCES iam.specializations(id) ON DELETE RESTRICT,
    code varchar(50) NOT NULL,
    name varchar(150) NOT NULL,
    description text,
    price numeric(10, 2) NOT NULL DEFAULT 0.00 CHECK (price >= 0),
    standard_validity_days integer NOT NULL DEFAULT 365 CHECK (standard_validity_days > 0),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uq_services_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS dossier.folder_templates (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id integer NOT NULL REFERENCES dossier.services(id) ON DELETE CASCADE,
    parent_id integer REFERENCES dossier.folder_templates(id) ON DELETE CASCADE,
    name varchar(150) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    CONSTRAINT uq_folder_templates_sibling UNIQUE (service_id, parent_id, name)
);
CREATE INDEX IF NOT EXISTS ix_folder_templates_service ON dossier.folder_templates(service_id);

CREATE TABLE IF NOT EXISTS dossier.cases (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_number varchar(50) NOT NULL,
    client_id integer NOT NULL REFERENCES iam.users(id) ON DELETE RESTRICT,
    service_id integer NOT NULL REFERENCES dossier.services(id) ON DELETE RESTRICT,
    specialization_id smallint REFERENCES iam.specializations(id) ON DELETE RESTRICT,
    assigned_operator_id integer REFERENCES iam.users(id) ON DELETE SET NULL,
    status varchar(30) NOT NULL DEFAULT 'Draft' 
        CHECK (status IN ('Draft', 'Inserted', 'InProgress', 'PendingDocuments', 'Sent', 'Completed', 'Rejected', 'Cancelled')),
    amount_paid numeric(10, 2) NOT NULL DEFAULT 0.00 CHECK (amount_paid >= 0),
    start_date date NOT NULL DEFAULT current_date,
    end_date date,
    reference_year smallint CHECK (reference_year >= 2000 AND reference_year <= 2100),
    notes text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz,
    version integer NOT NULL DEFAULT 1,
    CONSTRAINT uq_cases_number UNIQUE (case_number)
);

CREATE INDEX IF NOT EXISTS ix_cases_client ON dossier.cases(client_id);
CREATE INDEX IF NOT EXISTS ix_cases_operator ON dossier.cases(assigned_operator_id);
CREATE INDEX IF NOT EXISTS ix_cases_status ON dossier.cases(status);
CREATE INDEX IF NOT EXISTS ix_cases_service_year ON dossier.cases(service_id, reference_year);

CREATE OR REPLACE TRIGGER trg_cases_touch
BEFORE UPDATE ON dossier.cases
FOR EACH ROW EXECUTE FUNCTION system.touch_updated_at();

-- ============================================================================
-- SCHEMA: dms (Document Management System)
-- ============================================================================

CREATE TABLE IF NOT EXISTS dms.storage_providers (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL,
    provider_type varchar(30) NOT NULL CHECK (provider_type IN ('LocalStorage', 'AzureBlob', 'Ftp', 'S3')),
    base_endpoint text NOT NULL,
    container_or_bucket varchar(150) NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_storage_providers_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS dms.categories (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    description text,
    CONSTRAINT uq_document_categories_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS dms.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id integer NOT NULL REFERENCES iam.users(id) ON DELETE RESTRICT,
    case_id integer REFERENCES dossier.cases(id) ON DELETE SET NULL,
    folder_template_id integer REFERENCES dossier.folder_templates(id) ON DELETE SET NULL,
    category_id smallint REFERENCES dms.categories(id) ON DELETE RESTRICT,
    
    file_name varchar(255) NOT NULL,
    file_extension varchar(20) NOT NULL,
    mime_type varchar(150) NOT NULL,
    file_size_bytes bigint NOT NULL CHECK (file_size_bytes >= 0),
    
    storage_provider_id smallint NOT NULL REFERENCES dms.storage_providers(id) ON DELETE RESTRICT,
    storage_relative_path text NOT NULL,
    content_sha256 char(64),
    
    reference_year smallint CHECK (reference_year IS NULL OR (reference_year >= 2000 AND reference_year <= 2100)),
    description text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    
    uploaded_by_user_id integer NOT NULL REFERENCES iam.users(id) ON DELETE RESTRICT,
    uploaded_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz,
    version integer NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS ix_documents_client ON dms.documents(client_id);
CREATE INDEX IF NOT EXISTS ix_documents_case ON dms.documents(case_id);
CREATE INDEX IF NOT EXISTS ix_documents_category ON dms.documents(category_id);
CREATE INDEX IF NOT EXISTS ix_documents_sha256 ON dms.documents(content_sha256);
CREATE INDEX IF NOT EXISTS ix_documents_uploaded_at ON dms.documents(uploaded_at DESC);

CREATE OR REPLACE TRIGGER trg_documents_touch
BEFORE UPDATE ON dms.documents
FOR EACH ROW EXECUTE FUNCTION system.touch_updated_at();

-- ============================================================================
-- SCHEMA: scheduling (Appuntamenti con vincolo GIST)
-- ============================================================================

CREATE TABLE IF NOT EXISTS scheduling.appointments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id integer NOT NULL REFERENCES iam.users(id) ON DELETE RESTRICT,
    operator_id integer NOT NULL REFERENCES iam.users(id) ON DELETE RESTRICT,
    case_id integer REFERENCES dossier.cases(id) ON DELETE SET NULL,
    
    time_window tstzrange NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'Scheduled' 
        CHECK (status IN ('Scheduled', 'Approved', 'Confirmed', 'Completed', 'Cancelled', 'NoShow')),
    notes text,
    show_in_global_calendar boolean NOT NULL DEFAULT true,
    
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz,
    version integer NOT NULL DEFAULT 1,
    
    CONSTRAINT no_overlapping_operator_appointments 
        EXCLUDE USING gist (
            operator_id WITH =,
            time_window WITH &&
        ) WHERE (status NOT IN ('Cancelled', 'NoShow'))
);

CREATE INDEX IF NOT EXISTS ix_appointments_client ON scheduling.appointments(client_id);
CREATE INDEX IF NOT EXISTS ix_appointments_operator ON scheduling.appointments(operator_id);
CREATE INDEX IF NOT EXISTS ix_appointments_window ON scheduling.appointments USING gist (time_window);

CREATE OR REPLACE TRIGGER trg_appointments_touch
BEFORE UPDATE ON scheduling.appointments
FOR EACH ROW EXECUTE FUNCTION system.touch_updated_at();

-- ============================================================================
-- SCHEMA: system (Logs, Notifiche, Richieste, Import)
-- ============================================================================

CREATE TABLE IF NOT EXISTS system.app_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_level varchar(20) NOT NULL,
    message text NOT NULL,
    stack_trace text,
    source_context text,
    user_id integer REFERENCES iam.users(id) ON DELETE SET NULL,
    ip_address inet,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX IF NOT EXISTS ix_app_logs_level_date ON system.app_logs(log_level, created_at DESC);

CREATE TABLE IF NOT EXISTS system.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES iam.users(id) ON DELETE CASCADE,
    title varchar(200) NOT NULL,
    message text NOT NULL,
    type varchar(50) NOT NULL DEFAULT 'General',
    is_read boolean NOT NULL DEFAULT false,
    related_entity_type varchar(50),
    related_entity_id bigint,
    is_created_by_final_user boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX IF NOT EXISTS ix_notifications_user_read ON system.notifications(user_id, is_read);

CREATE TABLE IF NOT EXISTS system.user_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id integer NOT NULL REFERENCES iam.users(id) ON DELETE RESTRICT,
    receiver_id integer REFERENCES iam.users(id) ON DELETE SET NULL,
    request_type varchar(50) NOT NULL,
    subject varchar(200) NOT NULL,
    message text NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'Pending',
    response text,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    responded_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_user_requests_receiver ON system.user_requests(receiver_id);
CREATE INDEX IF NOT EXISTS ix_user_requests_sender ON system.user_requests(sender_id);

CREATE TABLE IF NOT EXISTS system.import_templates (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    target_entity varchar(50) NOT NULL,
    created_by_user_id integer NOT NULL REFERENCES iam.users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uq_import_templates_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS system.import_batches (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL,
    template_id smallint NOT NULL REFERENCES system.import_templates(id) ON DELETE RESTRICT,
    file_name varchar(255) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'Pending',
    progress smallint NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    error_message text,
    imported_data text,
    created_by_user_id integer NOT NULL REFERENCES iam.users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at timestamptz
);
