<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Auxilia.Persistence.Catalog\Auxilia.Persistence.Catalog.csproj" />
    <ProjectReference Include="..\..\src\Auxilia.Persistence.Tenant\Auxilia.Persistence.Tenant.csproj" />
    <ProjectReference Include="..\Auxilia.Tests.Common\Auxilia.Tests.Common.csproj" />
  </ItemGroup>

</Project>
