using Auxilia.Diagnostics;
using Auxilia.MigrationRunner.LegacyImport;

using Microsoft.EntityFrameworkCore;

using Npgsql;

namespace Auxilia.LegacyImport.Tests;

/// <summary>Reading the legacy database (task E-01): baselines, read model, read-only session, inventory.</summary>
[Collection(LegacyDatabaseGroup.Name)]
public sealed class LegacySourceTests(LegacyDatabaseFixture fixture)
{
    private static CancellationToken Ct => TestContext.Current.CancellationToken;

    [Fact]
    public async Task OpenAsync_DevelopBaseline_IsSupportedWithoutSecurityUpdate()
    {
        await using var source = await OpenAsync(LegacyDatabaseFixture.Develop);

        source.Schema.LastMigration.ShouldBe("20260602145759_AddMembershipFolderTemplate");
        source.Schema.HasSecurityUpdate.ShouldBeFalse();
        source.Schema.Variant.ShouldBe(new LegacyVariant(SecurityUpdate: false, ImportJobs: false));
        source.Schema.Unknown.ShouldBeEmpty();
    }

    [Fact]
    public async Task OpenAsync_SecurityUpdateBaseline_IsDetected()
    {
        await using var source = await OpenAsync(LegacyDatabaseFixture.SecurityUpdate);

        source.Schema.LastMigration.ShouldBe("20260623092237_AddSecurityFeatures");
        source.Schema.HasSecurityUpdate.ShouldBeTrue();
        source.Schema.Unknown.ShouldBeEmpty();
    }

    [Theory]
    [InlineData(LegacyDatabaseFixture.Develop)]
    [InlineData(LegacyDatabaseFixture.SecurityUpdate)]
    public async Task ReadModel_EveryMappedTable_IsReadable(string database)
    {
        await using var source = await OpenAsync(database);
        await using var db = source.CreateContext();

        (await db.Users.OrderBy(user => user.Id).ToListAsync(Ct)).Select(user => user.Username)
            .ShouldBe(["admin", "operatore", "cliente", "system", "orfano"]);
        (await db.Users.SingleAsync(user => user.Id == 3, Ct)).AssignedEmployeeId.ShouldBe(2);
        (await db.Roles.CountAsync(Ct)).ShouldBe(4);
        (await db.UserRoles.CountAsync(Ct)).ShouldBe(4);
        (await db.Languages.CountAsync(Ct)).ShouldBe(2);
        await db.RoleSpecializations.ToListAsync(Ct);
        await db.UserRoleSpecializations.ToListAsync(Ct);
        await db.MembershipTypes.ToListAsync(Ct);
        await db.Memberships.ToListAsync(Ct);
        await db.MembershipFolderTemplates.ToListAsync(Ct);
        await db.Subscriptions.ToListAsync(Ct);
        await db.UserDocuments.ToListAsync(Ct);
        await db.Appointments.ToListAsync(Ct);
        await db.Requests.ToListAsync(Ct);
        await db.Notifications.ToListAsync(Ct);
        await db.RegistrationRequests.ToListAsync(Ct);
        await db.ImportTypes.ToListAsync(Ct);
        await db.Imports.ToListAsync(Ct);
        await db.ResourceKeys.ToListAsync(Ct);
        await db.ResourceTranslations.ToListAsync(Ct);
        await db.SystemConfigurations.ToListAsync(Ct);
        await db.EmailConfigurations.ToListAsync(Ct);
        await db.ModuleConfigurations.ToListAsync(Ct);
        await db.PageConfigurations.ToListAsync(Ct);
        await db.EntityConfigurations.ToListAsync(Ct);
        if (db.Variant.SecurityUpdate)
        {
            await db.LoginAuditLogs.ToListAsync(Ct);
            await db.PasswordHistories.ToListAsync(Ct);
            (await db.Users.Select(user => user.PasswordChangedAt).ToListAsync(Ct)).ShouldAllBe(changed => changed == null);
        }
    }

    [Fact]
    public async Task ReadModel_ImportJobsTable_IsReadWhenPresent()
    {
        var connection = await fixture.CreateLegacyAsync("legacy_import_jobs", "legacy-develop.sql", """
            CREATE TABLE "ImportJobs" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "FileName" text NOT NULL, "ImportTypeId" integer NOT NULL,
                "Status" text NOT NULL, "TotalRows" integer NOT NULL, "ProcessedRows" integer NOT NULL, "SuccessRows" integer NOT NULL,
                "FailedRows" integer NOT NULL, "ErrorMessage" text, "StartedAt" timestamp with time zone,
                "CompletedAt" timestamp with time zone, "CreatedAt" timestamp with time zone NOT NULL, "CreatedByUserId" integer NOT NULL,
                "CustomFields" jsonb, "RowVersion" bytea);
            """);
        var opened = await LegacySource.OpenAsync(connection, Ct);
        await using var source = opened.Value;

        source.Schema.Variant.ImportJobs.ShouldBeTrue();
        await using var db = source.CreateContext();
        (await db.ImportJobs.CountAsync(Ct)).ShouldBe(0);
    }

    [Fact]
    public async Task OpenAsync_MissingBaselineTable_IsUnsupported()
    {
        var connection = await fixture.CreateLegacyAsync("legacy_without_requests", "legacy-develop.sql", """DROP TABLE "Requests";""");

        var opened = await LegacySource.OpenAsync(connection, Ct);

        opened.IsFailure.ShouldBeTrue();
        opened.Error!.Code.ShouldBe(EventCodes.Runner.LegacySchemaUnsupported);
        opened.Error.Description.ShouldContain("Requests");
    }

    [Fact]
    public async Task OpenAsync_MissingColumn_IsUnsupported()
    {
        var connection = await fixture.CreateLegacyAsync(
            "legacy_without_folder", "legacy-develop.sql", """ALTER TABLE "UserDocuments" DROP COLUMN "FolderTemplateId";""");

        var opened = await LegacySource.OpenAsync(connection, Ct);

        opened.Error!.Code.ShouldBe(EventCodes.Runner.LegacySchemaUnsupported);
        opened.Error.Description.ShouldContain("UserDocuments.FolderTemplateId");
    }

    [Fact]
    public async Task OpenAsync_UnreachableServer_IsUnavailable()
    {
        var opened = await LegacySource.OpenAsync("Host=127.0.0.1;Port=1;Database=x;Username=x;Timeout=2", Ct);

        opened.Error!.Code.ShouldBe(EventCodes.Runner.LegacySourceUnavailable);
    }

    [Fact]
    public async Task Session_IsReadOnly()
    {
        await using var source = await OpenAsync(LegacyDatabaseFixture.Develop);
        await using var db = source.CreateContext();

        var write = await Should.ThrowAsync<PostgresException>(() =>
            db.Database.ExecuteSqlRawAsync("""UPDATE "Users" SET "IsActive" = FALSE""", Ct));

        write.SqlState.ShouldBe(PostgresErrorCodes.ReadOnlySqlTransaction);
        await Should.ThrowAsync<InvalidOperationException>(() => db.SaveChangesAsync(Ct));
    }

    [Fact]
    public async Task Inventory_CountsRowsAndTheUsersLeftOut()
    {
        await using var source = await OpenAsync(LegacyDatabaseFixture.Develop);

        var inventory = await LegacyInventory.ReadAsync(source, Ct);

        Rows(inventory, "Users").ShouldBe(5);
        Rows(inventory, "WorkoutPlans").ShouldBe(1);
        Rows(inventory, "Requests").ShouldBe(0);
        Rows(inventory, "PasswordHistories").ShouldBeNull();
        Rows(inventory, "ImportJobs").ShouldBeNull();
        inventory.SystemUsers.ShouldBe(1);
        inventory.UsersWithoutRole.ShouldBe(1);
        inventory.TotalRows.ShouldBe(2 + 4 + 5 + 4 + 1);

        var report = LegacyReport.Render(inventory, mapped: null);
        report.ShouldContain("Security_Update no");
        report.ShouldContain("WorkoutPlans");
        report.ShouldContain("users not migrated (SystemConfigurator only, D-18): 1; users without a role: 1");
        report.ShouldNotContain("example.test");
    }

    [Fact]
    public async Task Inventory_SecurityUpdate_CountsItsTables()
    {
        await using var source = await OpenAsync(LegacyDatabaseFixture.SecurityUpdate);

        var inventory = await LegacyInventory.ReadAsync(source, Ct);

        Rows(inventory, "PasswordHistories").ShouldBe(0);
        Rows(inventory, "LoginAuditLogs").ShouldBe(0);
        Rows(inventory, "PasswordResetTokens").ShouldBe(0);
        LegacyReport.Render(inventory, mapped: null).ShouldContain("Security_Update yes");
    }

    private static long? Rows(LegacyInventory inventory, string table) =>
        inventory.Tables.Single(count => count.Table.Name == table).Rows;

    private async Task<LegacySource> OpenAsync(string database)
    {
        var opened = await LegacySource.OpenAsync(fixture.ConnectionString(database), Ct);
        opened.IsSuccess.ShouldBeTrue(opened.Error?.Description);
        return opened.Value;
    }
}
