// GENERATED by `pnpm --filter @auxilia/api-client generate` from backend/openapi/v1.json — do not edit.
// Placeholder until the API publishes its OpenAPI document (task P1-04 / P3-04).
export interface paths {}
export interface components {}
