namespace Auxilia.Diagnostics;

/// <summary>
/// Typed log entries generated by <c>[LoggerMessage]</c>, one nested class per <see cref="EventCodes"/> range.
/// <c>EventId</c> is the event code and <c>EventName</c> is <c>&lt;Range&gt;.&lt;CodeName&gt;</c>. Production code logs
/// Information and above only through these methods (verified by architecture tests). Message templates and
/// parameters never carry passwords, tokens, connection strings, full fiscal codes or document contents.
/// </summary>
public static partial class Log;
