-- Legacy schema at the baseline Security_Update @ e314e9a (tag legacy-baseline-security-update), D-30.
-- Generated with `dotnet ef migrations script` from the legacy Auxilia.Model at that tag: DDL only, no data.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AppLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Level" text NOT NULL,
    "Message" text NOT NULL,
    "StackTrace" text,
    "Source" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" integer,
    "IpAddress" text,
    CONSTRAINT "PK_AppLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "EmailConfigurations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SmtpServer" text NOT NULL,
    "SmtpPort" integer NOT NULL,
    "EnableSsl" boolean NOT NULL,
    "Username" text NOT NULL,
    "Password" text NOT NULL,
    "FromEmail" text NOT NULL,
    "FromName" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_EmailConfigurations" PRIMARY KEY ("Id")
);

CREATE TABLE "Languages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NOT NULL,
    "Name" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_Languages" PRIMARY KEY ("Id")
);

CREATE TABLE "Memberships" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Price" numeric NOT NULL,
    "DurationDays" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Memberships" PRIMARY KEY ("Id")
);

CREATE TABLE "ResourceKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NOT NULL,
    "Category" text NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_ResourceKeys" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "SystemConfigurations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(100) NOT NULL,
    "Value" text NOT NULL,
    "Description" character varying(200),
    "UpdatedAt" timestamp with time zone NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_SystemConfigurations" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text,
    "FiscalCode" text,
    "ProfileImage" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDefaultEmployee" boolean NOT NULL,
    "EnableConfigurationSettings" boolean NOT NULL,
    "LanguageId" integer NOT NULL,
    "AssignedEmployeeId" integer,
    "AssignedAdministratorId" integer,
    "RowVersion" bytea,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Users_AssignedAdministratorId" FOREIGN KEY ("AssignedAdministratorId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_Users_Users_AssignedEmployeeId" FOREIGN KEY ("AssignedEmployeeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ResourceTranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ResourceKeyId" integer NOT NULL,
    "LanguageId" integer NOT NULL,
    "Value" text NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_ResourceTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ResourceTranslations_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ResourceTranslations_ResourceKeys_ResourceKeyId" FOREIGN KEY ("ResourceKeyId") REFERENCES "ResourceKeys" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Appointments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" integer NOT NULL,
    "EmployeeId" integer NOT NULL,
    "ScheduledDate" timestamp with time zone NOT NULL,
    "DurationMinutes" integer NOT NULL,
    "Status" text NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_Users_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Appointments_Users_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Imports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ImportTypeId" integer NOT NULL,
    "FileName" text NOT NULL,
    "Status" text NOT NULL,
    "Progress" integer NOT NULL,
    "ErrorMessage" text,
    "ImportedData" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "CreatedByUserId" integer NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_Imports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Imports_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ImportTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "TargetEntity" text NOT NULL,
    "ColumnMapping" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByUserId" integer NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_ImportTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ImportTypes_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Type" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RelatedEntityId" integer,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RegistrationRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Phone" character varying(20) NOT NULL,
    "FiscalCode" character varying(16) NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "RequestDate" timestamp with time zone NOT NULL,
    "IsProcessed" boolean NOT NULL,
    "ProcessedByUserId" integer,
    "ProcessedDate" timestamp with time zone,
    "Notes" text,
    "RowVersion" bytea,
    CONSTRAINT "PK_RegistrationRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RegistrationRequests_Users_ProcessedByUserId" FOREIGN KEY ("ProcessedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Requests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer,
    "Type" text NOT NULL,
    "Subject" text NOT NULL,
    "Message" text NOT NULL,
    "Status" text NOT NULL,
    "Response" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RespondedAt" timestamp with time zone,
    CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Requests_Users_ReceiverId" FOREIGN KEY ("ReceiverId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Requests_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Subscriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "MembershipId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "AmountPaid" numeric NOT NULL,
    "RowVersion" bytea,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subscriptions_Memberships_MembershipId" FOREIGN KEY ("MembershipId") REFERENCES "Memberships" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Subscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ConnectionId" text NOT NULL,
    "IpAddress" text NOT NULL,
    "UserAgent" text NOT NULL,
    "LoginTime" timestamp with time zone NOT NULL,
    "LastActivity" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_UserSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WorkoutPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" integer NOT NULL,
    "CreatedByEmployeeId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Exercises" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WorkoutPlans" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkoutPlans_Users_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Appointments_ClientId" ON "Appointments" ("ClientId");

CREATE INDEX "IX_Appointments_EmployeeId" ON "Appointments" ("EmployeeId");

CREATE INDEX "IX_Imports_CreatedByUserId" ON "Imports" ("CreatedByUserId");

CREATE INDEX "IX_ImportTypes_CreatedByUserId" ON "ImportTypes" ("CreatedByUserId");

CREATE UNIQUE INDEX "IX_Languages_Code" ON "Languages" ("Code");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE UNIQUE INDEX "IX_RegistrationRequests_Email" ON "RegistrationRequests" ("Email");

CREATE INDEX "IX_RegistrationRequests_ProcessedByUserId" ON "RegistrationRequests" ("ProcessedByUserId");

CREATE INDEX "IX_Requests_ReceiverId" ON "Requests" ("ReceiverId");

CREATE INDEX "IX_Requests_SenderId" ON "Requests" ("SenderId");

CREATE UNIQUE INDEX "IX_ResourceKeys_Key" ON "ResourceKeys" ("Key");

CREATE INDEX "IX_ResourceTranslations_LanguageId" ON "ResourceTranslations" ("LanguageId");

CREATE INDEX "IX_ResourceTranslations_ResourceKeyId" ON "ResourceTranslations" ("ResourceKeyId");

CREATE INDEX "IX_Subscriptions_MembershipId" ON "Subscriptions" ("MembershipId");

CREATE INDEX "IX_Subscriptions_UserId" ON "Subscriptions" ("UserId");

CREATE UNIQUE INDEX "IX_SystemConfigurations_Key" ON "SystemConfigurations" ("Key");

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

CREATE INDEX "IX_Users_AssignedAdministratorId" ON "Users" ("AssignedAdministratorId");

CREATE INDEX "IX_Users_AssignedEmployeeId" ON "Users" ("AssignedEmployeeId");

CREATE INDEX "IX_UserSessions_UserId" ON "UserSessions" ("UserId");

CREATE INDEX "IX_WorkoutPlans_ClientId" ON "WorkoutPlans" ("ClientId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251206194606_InitialPostgreSQL', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "ImportTypes" DROP COLUMN "ColumnMapping";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251207164711_RemoveColumnMappingFromImportType', '10.0.0');

COMMIT;

START TRANSACTION;
CREATE TABLE "UserDocuments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "FileType" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "UploadedByUserId" integer NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    "Description" text,
    "RowVersion" bytea,
    CONSTRAINT "PK_UserDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserDocuments_Users_UploadedByUserId" FOREIGN KEY ("UploadedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_UserDocuments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_UserDocuments_UploadedByUserId" ON "UserDocuments" ("UploadedByUserId");

CREATE INDEX "IX_UserDocuments_UserId" ON "UserDocuments" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251208172626_AddUserDocuments', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "DateOfBirth" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260106145715_UserBirthDate', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "IsCaf" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Users" ADD "IsPatron" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260111165802_AddIsCafIsPatronToUser', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "PrivacyConsent" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260122203522_AddPrivacyConsentToUser', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "CustomFields" jsonb;

ALTER TABLE "UserDocuments" ADD "CustomFields" jsonb;

ALTER TABLE "SystemConfigurations" ADD "CustomFields" jsonb;

ALTER TABLE "Subscriptions" ADD "CustomFields" jsonb;

ALTER TABLE "ResourceTranslations" ADD "CustomFields" jsonb;

ALTER TABLE "ResourceKeys" ADD "CustomFields" jsonb;

ALTER TABLE "RegistrationRequests" ADD "CustomFields" jsonb;

ALTER TABLE "Languages" ADD "CustomFields" jsonb;

ALTER TABLE "ImportTypes" ADD "CustomFields" jsonb;

ALTER TABLE "Imports" ADD "CustomFields" jsonb;

ALTER TABLE "EmailConfigurations" ADD "CustomFields" jsonb;

ALTER TABLE "Appointments" ADD "CustomFields" jsonb;

CREATE TABLE "EntityConfigurations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntityName" text NOT NULL,
    "Configuration" jsonb NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    "CustomFields" jsonb,
    CONSTRAINT "PK_EntityConfigurations" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_EntityConfigurations_EntityName" ON "EntityConfigurations" ("EntityName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260124154025_AddCustomFieldsAndEntityConfiguration', '10.0.0');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260124200950_RemoveIsCafIsPatronColumns', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" DROP COLUMN "IsCaf";

ALTER TABLE "Users" DROP COLUMN "IsPatron";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125100218_SyncPendingChanges', '10.0.0');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125100408_RemoveDuplicateCustomFields', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Notifications" ADD "IsCreatedByFinalUser" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125133357_NotificationCreatedByFinalUser', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Appointments" ADD "ShowInGlobalCalendare" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125142746_ShowGlobalAppointment', '10.0.0');

COMMIT;

START TRANSACTION;
CREATE TABLE "PageConfigurations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PageName" text NOT NULL,
    "ParentPageId" integer,
    "Role" text NOT NULL,
    "ConfigurationGrid" jsonb,
    "IsEnabled" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    "CustomFields" jsonb,
    CONSTRAINT "PK_PageConfigurations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PageConfigurations_PageConfigurations_ParentPageId" FOREIGN KEY ("ParentPageId") REFERENCES "PageConfigurations" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_PageConfigurations_PageName_Role" ON "PageConfigurations" ("PageName", "Role");

CREATE INDEX "IX_PageConfigurations_ParentPageId" ON "PageConfigurations" ("ParentPageId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125155858_AddPageConfiguration', '10.0.0');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125160814_AddSystemConfiguratorRole', '10.0.0');

COMMIT;

START TRANSACTION;
CREATE TABLE "ModuleConfigurations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Role" text NOT NULL,
    "ModulePath" text NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    "CustomFields" jsonb,
    CONSTRAINT "PK_ModuleConfigurations" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_ModuleConfigurations_Role_ModulePath" ON "ModuleConfigurations" ("Role", "ModulePath");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260125161710_AddModuleConfiguration', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "UserDocuments" ADD "ReferenceYear" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260131205720_AddReferenceYearToUserDocument', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "UserDocuments" ADD "Area" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260131211411_AddAreaToUserDocument', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "UserDocuments" ADD "SubscriptionId" integer;

ALTER TABLE "Subscriptions" ALTER COLUMN "EndDate" DROP NOT NULL;

ALTER TABLE "Subscriptions" ADD "Status" integer NOT NULL DEFAULT 0;

ALTER TABLE "Memberships" ADD "MembershipTypeId" integer;

CREATE TABLE "MembershipTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_MembershipTypes" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_UserDocuments_SubscriptionId" ON "UserDocuments" ("SubscriptionId");

CREATE INDEX "IX_Memberships_MembershipTypeId" ON "Memberships" ("MembershipTypeId");

ALTER TABLE "Memberships" ADD CONSTRAINT "FK_Memberships_MembershipTypes_MembershipTypeId" FOREIGN KEY ("MembershipTypeId") REFERENCES "MembershipTypes" ("Id") ON DELETE RESTRICT;

ALTER TABLE "UserDocuments" ADD CONSTRAINT "FK_UserDocuments_Subscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES "Subscriptions" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260214100118_SubscriptionWorkflow', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Subscriptions" ADD "IsRejected" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260307183610_AddIsRejectedToSubscription', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "Surname" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260314152604_AddSurnameToUser', '10.0.0');

COMMIT;

START TRANSACTION;
CREATE TABLE "RoleSpecializations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Email" text NOT NULL,
    "WorkNumber" text NOT NULL,
    "PrivateSubscriptions" boolean NOT NULL,
    "RoleId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_RoleSpecializations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleSpecializations_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "UserRoleSpecializations" (
    "UserId" integer NOT NULL,
    "RoleSpecializationId" integer NOT NULL,
    "AssignedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserRoleSpecializations" PRIMARY KEY ("UserId", "RoleSpecializationId"),
    CONSTRAINT "FK_UserRoleSpecializations_RoleSpecializations_RoleSpecializat~" FOREIGN KEY ("RoleSpecializationId") REFERENCES "RoleSpecializations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoleSpecializations_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RoleSpecializations_RoleId" ON "RoleSpecializations" ("RoleId");

CREATE INDEX "IX_UserRoleSpecializations_RoleSpecializationId" ON "UserRoleSpecializations" ("RoleSpecializationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260413174812_AddRoleSpecializations', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Subscriptions" ADD "RoleSpecializationId" integer;

CREATE INDEX "IX_Subscriptions_RoleSpecializationId" ON "Subscriptions" ("RoleSpecializationId");

ALTER TABLE "Subscriptions" ADD CONSTRAINT "FK_Subscriptions_RoleSpecializations_RoleSpecializationId" FOREIGN KEY ("RoleSpecializationId") REFERENCES "RoleSpecializations" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260413182320_AddRoleSpecializationToSubscription', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Memberships" ADD "RoleSpecializationId" integer;

CREATE INDEX "IX_Memberships_RoleSpecializationId" ON "Memberships" ("RoleSpecializationId");

ALTER TABLE "Memberships" ADD CONSTRAINT "FK_Memberships_RoleSpecializations_RoleSpecializationId" FOREIGN KEY ("RoleSpecializationId") REFERENCES "RoleSpecializations" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260413183439_AddRoleSpecializationToMembership', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "UserDocuments" ADD "FolderTemplateId" integer;

CREATE TABLE "MembershipFolderTemplates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MembershipId" integer NOT NULL,
    "Name" text NOT NULL,
    "ParentId" integer,
    "SortOrder" integer NOT NULL,
    CONSTRAINT "PK_MembershipFolderTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MembershipFolderTemplates_MembershipFolderTemplates_ParentId" FOREIGN KEY ("ParentId") REFERENCES "MembershipFolderTemplates" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MembershipFolderTemplates_Memberships_MembershipId" FOREIGN KEY ("MembershipId") REFERENCES "Memberships" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_UserDocuments_FolderTemplateId" ON "UserDocuments" ("FolderTemplateId");

CREATE INDEX "IX_MembershipFolderTemplates_MembershipId" ON "MembershipFolderTemplates" ("MembershipId");

CREATE INDEX "IX_MembershipFolderTemplates_ParentId" ON "MembershipFolderTemplates" ("ParentId");

ALTER TABLE "UserDocuments" ADD CONSTRAINT "FK_UserDocuments_MembershipFolderTemplates_FolderTemplateId" FOREIGN KEY ("FolderTemplateId") REFERENCES "MembershipFolderTemplates" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260602145759_AddMembershipFolderTemplate', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "PasswordChangedAt" timestamp with time zone;

CREATE TABLE "LoginAuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "Username" text NOT NULL,
    "LoginAt" timestamp with time zone NOT NULL,
    "IpAddress" text,
    "LoginType" text NOT NULL,
    "Success" boolean NOT NULL,
    "FailureReason" text,
    CONSTRAINT "PK_LoginAuditLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LoginAuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE TABLE "PasswordHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PasswordHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PasswordHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PasswordHistories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PasswordResetTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Token" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_LoginAuditLogs_UserId" ON "LoginAuditLogs" ("UserId");

CREATE INDEX "IX_PasswordHistories_UserId" ON "PasswordHistories" ("UserId");

CREATE UNIQUE INDEX "IX_PasswordResetTokens_Token" ON "PasswordResetTokens" ("Token");

CREATE INDEX "IX_PasswordResetTokens_UserId" ON "PasswordResetTokens" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260623092237_AddSecurityFeatures', '10.0.0');

COMMIT;

